services:
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ../.env
    ports:
      - '5432:5432'
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  scraper:
    build:
      context: ..
      dockerfile: scraper/scraper.dockerfile
    env_file:
      - ../.env
    depends_on:
      db:
        condition: service_healthy
    restart: "no"

  app:
    build:
      context: ..
      dockerfile: app/dash.dockerfile
    restart: always
    env_file:
      - ../.env
    ports:
      - '8000:8000'
    depends_on:
      scraper:
        condition: service_completed_successfully
      db:
        condition: service_healthy

volumes:
  postgres_data:
